FROM golang:1.20.4-bullseye

ARG TARGETARCH

ARG GOLANGCI_LINT_VERSION=1.52.2

RUN cd /usr/local/bin \
    && curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-${TARGETARCH}.tar.gz \
        | tar xvz golangci-lint-${GOLANGCI_LINT_VERSION}-linux-${TARGETARCH}/golangci-lint --strip-components=1
